variable "instance_type" {}
variable "subnet_ids" {}
variable "name" {}
variable "env" {}
variable "app_cidr_block" {}
variable "vpc_id" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}